### ISSUE TITLE
Implement flexbox on card list

### ISSUE THREAD

**Issue by camisetags** [gabrielSeixas/total_loss#12]

**Comment by anshumanv** [comment]
I'll do this

**Comment by anshumanv** [comment]
Just to be sure, you're referring to https://github.com/gabrielSeixas/total-loss/blob/a3f78b04bc8327f935eb05e4d77440f0b9f11abd/src/styles/_card.scss#L1 this right ?

**Comment by camisetags** [comment]
Yes! I just want to group the card list on [https://github.com/gabrielSeixas/total-loss/blob/develop/src/app/deck/pages/DeckSelect/component.jsx](url)

**Comment by anshumanv** [comment]
Alright, will add flex in a while

**Comment by andrewgreenh** [comment]
@anshumanv You still working on this? Otherwise I'd like to take a shot :)

**Comment by anshumanv** [comment]
I totally forgot about this, please go ahead @andreasgruenh 👍

**Comment by andrewgreenh** [comment]
I think this ticket needs a bit more explanation :D just cloned this repo and looked at the source code and I cannot tell where you want to use flexbox for what purpose.

**Comment by camisetags** [comment]
@andreasgruenh the purpose is just to group the card list side by side.

**Comment by pgsill** [comment]
Done. No one else seemed to be working on the issue, so I went ahead and did it myself.

🥇

**Comment by camisetags** [comment]
@pgsil WELL DONE!! EXCELLENT JOB!
