### ISSUE TITLE
Create Loading component

### ISSUE THREAD

**Issue by camisetags** [gabrielSeixas/total_loss#18]
Create a component to show the load state of the page.

**Comment by pgsil** [comment]
@gabrielSeixas Can I do this one as well?

**Comment by pgsill** [comment]
@gabrielSeixas Can I do this one as well?

**Comment by camisetags** [comment]
Okay.

**Comment by abhishek71994** [comment]
In case @pgsil wants to focus on some other issue. I would like to work on this one.
