### ISSUE TITLE
Create resources for user module

### ISSUE THREAD

**Issue by camisetags** [gabrielSeixas/total_loss#19]
Create actions, reducers and stuff to allow user to play the game:

- [ ]  User score
- [ ]  Accept card challenge

Example of user initial state:
`[{
username: 'example',
score: 0,
}]`

**Comment by lucasssm** [comment]
Will take a look on that!

**Comment by lucasssm** [comment]
Never mind... all these jsx syntax and unused dependencies made everything so messy... I couldn't even write a simple return without getting a ton of errors about semicolons and unexpected tokens...
I recommend you guys to take advantage of this still is a beginner project and restart everything to make things more simple, there's just to many complications for a project in this size.
Any way, just a tip! Sorry for not contribute to anything.

**Comment by sahiljain95** [comment]
What is this game supposed to do ? I couldn't quite figure it out
