### ISSUE TITLE
Fix toilet seat on bottom of screen.

### ISSUE THREAD

**Issue by camisetags** [gabrielSeixas/total_loss#36]
Toilet seat must be always on bottom of the screen. Like this:

![screen shot 2017-10-27 at 10 11 19](https://user-images.githubusercontent.com/5252228/32103494-69789008-baff-11e7-9371-0b3a861c452b.png)

**Comment by SidduH** [comment]
I cannot run this app, as i'm getting error, " Error: Cannot find module 'node-sass'" kindly let me know, How can I proceed.. I'm using 'npm'
